services:
    wireguard:
        image: lscr.io/linuxserver/wireguard:latest
        container_name: wireguard
        cap_add:
          - NET_ADMIN
        environment:
            - PUID=0
            - PGID=0
            - TZ=Europe/Paris
            - SERVERURL=auto
            - PEERS=fierceDeity,exelo,taya
            - PEERDNS=172.18.0.20
            - PERSITENTKEEPALIVE_PEERS=all
            - LOG_CONFS=false
        volumes:
            - /home/dawn/docker/wireguard/config:/config
        ports:
            - 51820:51820/udp
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
            - net.ipv4.ip_forward=1
        restart: unless-stopped
    heimdall:
        image: lscr.io/linuxserver/heimdall:latest
        container_name: heimdall
        environment:
            - TZ=Europe/Paris
        networks:
            default:
                ipv4_address: 172.18.0.10
        restart: unless-stopped
    transmission:
        image: lscr.io/linuxserver/transmission:latest
        container_name: transmission
        environment:
            - PUID=0
            - PGID=0
            - TZ=Europe/Paris
        volumes:
            - /media/bellum/gohma/data:/config
            - /media/bellum/gohma/downloads:/downloads
            - /media/bellum/gohma/watchdir:/watch
        networks:
            default:
                ipv4_address: 172.18.0.11
        restart: unless-stopped
    sonarr:
        image: lscr.io/linuxserver/sonarr:latest
        container_name: sonarr
        environment:
            - PUID=0
            - PGID=0
            - TZ=Europe/Paris
        volumes:
            - /home/dawn/docker/sonarr:/config
            - /media/bellum/gohma/downloads:/downloads
            - /media/bellum/main/Multimédia/Séries:/tv
        networks:
            default:
                ipv4_address: 172.18.0.12
        restart: unless-stopped
    radarr:
        image: lscr.io/linuxserver/radarr:latest
        container_name: radarr
        environment:
            - PUID=0
            - PGID=0
            - TZ=Europe/Paris
        volumes:
            - /home/dawn/docker/radarr:/config
            - /media/bellum/gohma/downloads:/downloads
            - /media/bellum/main/Multimédia/Films:/movies
        networks:
            default:
                ipv4_address: 172.18.0.13
        restart: unless-stopped
    jackett:
        image: lscr.io/linuxserver/jackett:latest
        container_name: jackett
        environment:
            - PUID=0
            - PGID=0
            - TZ=Europe/Paris
            - AUTO_UPDATE=true
        volumes:
            - /home/dawn/docker/jackett:/config
        networks:
            default:
                ipv4_address: 172.18.0.14
        restart: unless-stopped
    bazarr:
        image: lscr.io/linuxserver/bazarr:latest
        container_name: bazarr
        environment:
            - PUID=0
            - PGID=0
            - TZ=Europe/Paris
        volumes:
            - /home/dawn/docker/bazarr:/config
            - /media/bellum/main/Multimédia/Films:/movies
            - /media/bellum/main/Multimédia/Séries:/tv
        networks:
            default:
                ipv4_address: 172.18.0.15
        restart: unless-stopped
    jellyfin:
        image: lscr.io/linuxserver/jellyfin:latest
        container_name: jellyfin
        environment:
            - PUID=0
            - PGID=0
            - TZ=Europe/Paris
            - DOCKER_MODS=linuxserver/mods:jellyfin-amd
            - DOCKER_MODS=ghcr.io/intro-skipper/intro-skipper-docker-mod
        volumes:
            - /media/bellum/main/Multimédia/Films:/data/movies
            - /media/bellum/main/Multimédia/Séries:/data/tvshows
            - /media/bellum/main/new_Deezer:/data/music
            - /media/bellum/jellyfin:/config
        devices:
            - /dev/dri:/dev/dri
            - /dev/kfd:/dev/kfd
        networks:
            default:
                ipv4_address: 172.18.0.16
        restart: 'unless-stopped'
    lidarr:
        image: youegraillot/lidarr-on-steroids
        container_name: lidarr-on-steroids
        environment:
            - PUID=0
            - PGID=0
            - TZ=Europe/Paris
        volumes:
            - /media/bellum/main/new_Deezer:/music
            - /media/bellum/main/new_Deezer:/downloads
        networks:
            default:
                ipv4_address: 172.18.0.17
        restart: unless-stopped
    nginx:
        image: lscr.io/linuxserver/nginx:latest
        container_name: nginx
        environment:
            - PUID=0
            - PGID=0
            - TZ=Europe/Paris
        volumes:
            - /home/dawn/docker/nginx/config:/config
        networks:
            default:
                ipv4_address: 172.18.0.18
        restart: unless-stopped
    proxy-manager:
        image: 'jc21/nginx-proxy-manager:latest'
        container_name: 'proxy-manager'
        environment:
            PUID: 0
            PGID: 0
        volumes:
            - /home/dawn/docker/proxy-manager/data:/data
            - /home/dawn/docker/proxy-manager/letsencrypt:/etc/letsencrypt
        networks:
            default:
                ipv4_address: 172.18.0.19
        restart: unless-stopped
    pihole:
        image: pihole/pihole:latest
        container_name: pihole
        environment:
            TZ: 'Europe/Paris'
            FTLCONF_webserver_api_password: 'admin'
            FTLCONF_dns_listeningMode: 'all' # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
        networks:
            default:
                ipv4_address: 172.18.0.20
        restart: unless-stopped
    # vaultwarden:
    #     image: vaultwarden/server:latest
    #     container_name: vaultwarden
    #     environment:
    #         PUID: 0
    #         PGID: 0
    #         DOMAIN: "https://vaultwarden.$$DNS$$/"
    #         SIGNUPS_ALLOWED: "false"
    #     volumes:
    #         - /home/dawn/docker/vaultwarden/data:/data
    #     networks:
    #         default:
    #             ipv4_address: 172.18.0.21
    #     restart: unless-stopped
