# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
	imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

	boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
	boot.initrd.kernelModules = [ ];
	boot.kernelModules = [ "kvm-amd" ];
	boot.extraModulePackages = [ ];
	
	boot.initrd.luks.devices."luks-a9f364e5-9001-4a2a-88d1-ee36356ea91d".device = "/dev/disk/by-uuid/a9f364e5-9001-4a2a-88d1-ee36356ea91d";

	fileSystems."/" = {
		device = "/dev/disk/by-uuid/c5da878a-7edb-43d9-9b0e-3cd3c5eedaaf";
		fsType = "ext4";
	};
	fileSystems."/boot" = {
		device = "/dev/disk/by-uuid/B8B7-B686";
		fsType = "vfat";
		options = [ "fmask=0077" "dmask=0077" ];
	};
	fileSystems."/run/media/dawn/odolwa" = {
		device = "/dev/disk/by-uuid/aa579304-9b54-4b98-b4fe-d786bf28b40B";
		fsType = "btrfs";
		options = [ "subvol=log" "compress=zstd" "noatime" ];
	};

	# Enables DHCP on each ethernet and wireless interface. In case of scripted networking
	# (the default) this is the recommended approach. When using systemd-networkd it's
	# still possible to use this option, but it's recommended to use it in conjunction
	# with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
	networking.useDHCP = lib.mkDefault true;
	# networking.interfaces.enp39s0.useDHCP = lib.mkDefault true;
	# networking.interfaces.wlp37s0.useDHCP = lib.mkDefault true;

	nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
